import { describe, expect, it } from "vitest";
import {
  composeIssueBodyWithMetadata,
  extractIssueDateMetadata,
  stripIssueMetadataSection,
} from "./issueMetadata";

describe("issueMetadata", () => {
  it("embeds metadata in hidden autogenerated body section", () => {
    const body = composeIssueBodyWithMetadata("User description", {
      startDate: "2026-04-01",
      endDate: "2026-04-08",
      dueDate: "2026-04-10",
    });

    expect(body).toContain("<!-- prismtrack:auto-dates:start -->");
    expect(body).toContain("\"startDate\": \"2026-04-01\"");
    expect(body).toContain("<!-- prismtrack:auto-dates:end -->");
  });

  it("extracts metadata and returns preview-safe clean body", () => {
    const raw = composeIssueBodyWithMetadata("Visible content", {
      startDate: "2026-05-01",
      dueDate: "2026-05-15",
    });

    const parsed = extractIssueDateMetadata(raw);

    expect(parsed.cleanBody).toBe("Visible content");
    expect(parsed.metadata.startDate).toBe("2026-05-01");
    expect(parsed.metadata.endDate).toBeUndefined();
    expect(parsed.metadata.dueDate).toBe("2026-05-15");
  });

  it("removes autogenerated section when no metadata remains", () => {
    const raw = composeIssueBodyWithMetadata("Only text", {
      startDate: "2026-06-01",
    });
    const plain = composeIssueBodyWithMetadata(raw, {});

    expect(stripIssueMetadataSection(plain)).toBe("Only text");
    expect(plain).not.toContain("prismtrack:auto-dates:start");
  });
});
